"""PQR 解析回归（**不需要 pdb2pqr**，因此放在非 engine 组里，CI 也会跑）。

真实缺陷（run 20260922-140903-6542，受体 7YHP）：
    meeko 读取 PQR 失败（returncode=1）：
      File ".../meeko/polymer.py", line 2614, in atom_from_pqr_items
        resnum = int(atom_pqr_items.pop(0))
      ValueError: invalid literal for int() with base 10: '128.990'

根因：pdb2pqr 按 PDB **固定列**写 PQR。残基号到 4 位（7YHP 有 560–1xxx）时，链号与残基号
之间没有空格（`GLU A1005`），白空格切分只有 10 个 token；meeko 把 `A1005` 当链号、
把 x 坐标当残基号 → `int('128.990')` 崩。整条 pH 准备因此失败并静默回退标准流程
（报告里只写「未按目标 pH 重新准备」）。插入码（`36A`）是同一类粘连的另一半。
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Dict

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

#: 7YHP 真实 PQR 里触发缺陷的两行（残基号 1005，链 A）
FUSED_4DIGIT = "ATOM   2841  N   GLU A1005     128.990 117.515 122.728 -0.5163 1.8240\n"
NORMAL_3DIGIT = "ATOM      1  N   LYS A 560     104.561 111.076 111.444  0.0966 1.8240\n"
#: 7YHP 缓存产物（在仓库工作区里存在时做一次真实数据全量校验）
REAL_PQR = PROJECT_ROOT / "assets" / "cache" / "7YHP_f7f8da9b58da39a3_ph7.4.pqr"


def _atom(line: str) -> Dict[str, Any]:
    from docking_agent.core.receptor_ph import parse_pqr_atom_line

    parsed = parse_pqr_atom_line(line)
    assert parsed is not None, f"应当可解析：{line!r}"
    return parsed


def test_four_digit_resnum_fused_with_chain_is_split() -> None:
    """4 位残基号把链号挤没空格 → 必须拆成「链 / 残基号」两个 token（本次缺陷）。"""
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko

    fixed, changed = normalize_pqr_for_meeko(FUSED_4DIGIT)
    assert changed == 1
    tokens = fixed.split()
    assert tokens[3] == "GLU" and tokens[4] == "A" and tokens[5] == "1005", tokens[:6]
    # 关键：meeko 的 `resnum = int(token)` 现在拿到的一定是整数
    assert tokens[5].lstrip("-").isdigit()
    # 坐标与电荷/半径不得被改写丢精度
    assert tokens[6:11] == ["128.990", "117.515", "122.728", "-0.5163", "1.8240"]


def test_insertion_code_still_becomes_its_own_field() -> None:
    """插入码（既有行为）：`36A` → `36 A`，不得丢掉插入码。"""
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko

    fixed, changed = normalize_pqr_for_meeko("ATOM 1 N ILE H 36A 31.4 25.9 19.2 0.03 1.82\n")
    assert changed == 1
    assert fixed.split()[4:7] == ["H", "36", "A"], fixed


def test_chain_plus_four_digit_resnum_plus_icode() -> None:
    """链号 + 4 位残基号 + 插入码三者粘连也要拆对。"""
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko

    fixed, _ = normalize_pqr_for_meeko(
        "ATOM   2841  N   GLU A1005B    128.990 117.515 122.728 -0.5163 1.8240\n")
    assert fixed.split()[4:8] == ["A", "1005", "B", "128.990"], fixed


def test_already_canonical_lines_are_untouched() -> None:
    """规范形状（链与残基号已是独立 token）不得被改写（避免无谓的数值重排）。"""
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko

    fixed, changed = normalize_pqr_for_meeko(NORMAL_3DIGIT)
    assert changed == 0
    assert fixed.strip() == NORMAL_3DIGIT.strip()


def test_non_atom_lines_are_preserved() -> None:
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko

    text = "REMARK   1 generated by pdb2pqr\nTER\nATOM 1 N ILE H 36A 31.4 25.9 19.2 0.03 1.82\nEND\n"
    fixed, changed = normalize_pqr_for_meeko(text)
    assert changed == 1
    assert "REMARK   1 generated by pdb2pqr" in fixed and "\nTER\n" in fixed and "\nEND\n" in fixed


def test_his_states_use_residue_key_not_coordinates() -> None:
    """HIS 分组必须按「链+残基号」：4 位残基号以前会被当成链名，状态统计全错。"""
    from docking_agent.core.receptor_ph import his_states_from_pqr

    hip = ("ATOM   2841  N   HIS A1005     128.990 117.515 122.728 -0.5163 1.8240\n"
           "ATOM   2842  ND1 HIS A1005     129.990 117.515 122.728 -0.5163 1.8240\n"
           "ATOM   2843  HD1 HIS A1005     130.990 117.515 122.728  0.2000 1.0000\n"
           "ATOM   2844  NE2 HIS A1005     131.990 117.515 122.728 -0.5163 1.8240\n"
           "ATOM   2845  HE2 HIS A1005     132.990 117.515 122.728  0.2000 1.0000\n")
    assert his_states_from_pqr(hip) == {"HID": 0, "HIE": 0, "HIP": 1, "未判定": 0}


@pytest.mark.skipif(not REAL_PQR.is_file(), reason="工作区里没有 7YHP 的 PQR 产物")
def test_real_7yhp_pqr_becomes_meeko_parseable() -> None:
    """真实产物全量校验：规范化后每一行都满足 meeko 的字段假设（链/残基号各自独立）。"""
    from docking_agent.core.receptor_ph import normalize_pqr_for_meeko, parse_pqr_atom_line

    raw = REAL_PQR.read_text(encoding="utf-8", errors="ignore")
    atoms = [line for line in raw.splitlines() if line.startswith(("ATOM", "HETATM"))]
    assert len(atoms) > 1000, f"样本太小，疑似不是真实受体：{len(atoms)}"

    fixed, changed = normalize_pqr_for_meeko(raw)
    joined = fixed.splitlines()
    assert len(joined) == len(raw.splitlines()), "行数必须保持不变"
    for line in joined:
        if not line.startswith(("ATOM", "HETATM")):
            continue
        tokens = line.split()
        assert tokens[5].lstrip("-").isdigit(), f"残基号位仍是坐标：{line!r}"
        parsed = parse_pqr_atom_line(line)
        assert parsed is not None and 500 <= int(parsed["resnum"]) <= 2000, parsed
    # 7YHP 里确实存在 4 位残基号的行 → 本次修复确实覆盖到了它们
    non_canonical = [t for t in atoms if not t.split()[5].lstrip("-").isdigit()]
    assert non_canonical, "样本里没有 4 位残基号的行，测试失去意义"
    assert changed == len(non_canonical), (changed, len(non_canonical))
    # 3 位残基号的行必须**逐字不动**（不做无谓改写）
    canonical = [t for t in atoms if t.split()[5].lstrip("-").isdigit()]
    assert canonical and all(t in fixed for t in canonical[:50])
